x1=input('Digite algo: ')
print(f'O que você escreveu é do tipo {type(x1)}.')
print('Só tem espaços?',x1.isspace())
print('É um número?',x1.isnumeric())
print('É alfabético?',x1.isalpha())
print('É alfanumérico?',x1.isalnum())
print('Está somente em maiúsculas?',x1.isupper())
print('Está somente em minúsculas?',x1.islower())
print('Está capitalizada?',x1.istitle())